FROM node:8.0.0

# Create app directory

ENV APP_HOME /srv
ENV NODE_ENV development

WORKDIR $APP_HOME

COPY package.json $APP_HOME
# ADD ./node_modules /srv/app/node_modules
RUN npm install

COPY . $APP_HOME

# Set Environment variables at the end before running
ENV PORT 8000

EXPOSE 8000

CMD ["npm", "start"]
